#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 一 二 三 四 五 
bspc monitor HDMI-0 -d 六 七 八 九 十

bspc config border_width        0
bspc config window_gap          10

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config pointer_motion_interval 1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=floating
bspc rule -a Yad state=floating
bspc rule -a Nm-connection-editor state=floating
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color4"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color5"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
