#!/bin/sh

set -C -f

case "$(file --brief --mime-type "$1")" in
    image/*) mediainfo "$1" | sed "s/  */ /g" ;;
    text/* | xml | application/json) highlight -O ansi "$1" ;;
    audio/* | application/octet-stream | video/*) mediainfo "$1" | sed "s/  */ /g" || exit 1;;
    */pdf) pdfinfo "$1" ;;
    application/pgp-encrypted) gpg -d -- "$1" ;;
    application/*) file "$1" ;;
esac
